site:
  name: "Locomotive"
  locale: en
  meta_keywords: "cms open source ruby on rails heroku liquid rails3 cloud amazon S3 inline editing"
  meta_description: "LOCOMOTIVE is an open source CMS for Rails. It's super flexible and integrates with Heroku and Amazon S3."

  pages:
    - index:
        published: true
    - '404':
        title: "Page not found"
        published: true
    - 'about_us':
    - 'features':
    - 'hosting':
    - 'modules':
    - 'modules/template':
        title: Template of a module
        content_type: modules
        published: true
    - 'blog':
        redirect_url: 'http://blog.locomotivecms.com'
    - 'demo':
        tile: "Try demo"
        redirect_url: 'http://demo.locomotivecms.com'
        listed: false
    - 'support':
        title: 'Get started'
        redirect_url: '/support/installation'
        listed: false
    - 'support/installation':
        title: 'Installation guide'
    - 'support/installation/requirements':
        title: 'Requirements'
    - 'support/installation/source':
        title: 'From source installation'
    - 'support/installation/engine':
        title: 'Engine installation'
    - 'support/installation/heroku':
        title: 'Heroku deployment'
    - 'support/themes':
        title: 'Themes'
    - 'support/howto':
        title: "How-To's"
    - 'support/liquid':
        title: 'Liquid Syntax'
    - 'support/liquid/site':
        title: 'Site'
    - 'support/liquid/pages':
        title: 'Pages'
    - 'support/liquid/contents':
        title: 'Contents'
    - 'support/liquid/filters':
        title: 'Filters'
    - 'support/liquid/logic':
        title: 'Logic'
  assets:
    whitelist: ['/stylesheets/application.css', '/javascripts/application.js', '^/images/([^/]+)$']

  content_types:
    "News":
      description: Locomotive in the news
      slug: news
      order_by: posted_at
      highlighted_field_name: site_name
      fields:
        - site_name:
            hint: "Origin of the news (Techcrunch, WebAppers, ...etc)"
        - posted_at:
            hint: "Date of the news (mm d, yyyy)"
            kind: date
        - sentence:
            hint: "The piece of the article about Locomotive. Needs to be catchy"
        - url:
            hint: "The full url where the sentence comes from"
      contents:
          - "WebAppers":
              posted_at: "2011/01/18"
              sentence: "Locomotive is a powerful new Ruby on Rails CMS"
              url: http://www.webappers.com
          - "Techcrunch":
              posted_at: "2011/01/07"
              sentence: "Introducing Locomotive: the best CMS in the world"
              url: "http://www.techcrunch.com"

    "Crew":
      description: Members of the Locomotive team
      slug: crew # mandatory
      order_by: manually # manually / date / field slug #1, ...etc
      highlighted_field_name: name # mandatory
      fields:
        - name:
            hint: full name of the member
        - title:
            hint: position in the team
        - company:
            hint: company she/he works for
        - company_url:
            hint: Url of the company above
        - bio:
            kind: text
            hint: Short biography
        - plate:
            kind: file
            hint: Image
        - picture:
            kind: file
            hint: "Image (in the about us pagem), 154px x 180px"
      contents:
        - "Didier Lafforgue":
            title: "Rails developement"
            company: "NoCoffee"
            company_url: "http://www.nocoffee.fr"
            bio: "<p>Didier (<a href='http://www.twitter.com/dinedine31'>@Didier</a>) is the founder of Locomotive, he speaks, thinks, eats, sleeps CMS. His family and friends thank him to have created a simple system to edit their websites.</p>"
            plate: "/samples/contents/didier_plate.png"
            picture: "/samples/contents/conan.png"
        - "Jacques Crocker":
            title: "Rails developement"
            company: "RailsJedi.com"
            company_url: "http://www.railsjedi.com"
            bio: "<p>Jacques (<a href='http://twitter.com/railsjedi'>@railsjedi</a>) is a seasoned Rails developer with a passion for front end development. He loves using HAML, SASS, and Javascript to put together stunning user interfaces.</p>"
            plate: "/samples/contents/jacques_plate.png"
            picture: "/samples/contents/conan.png"
        - "Sacha Greif":
            title: "Design & UI"
            company: "SachaGreif.com"
            company_url: "http://www.sachagreif.com"
            bio: "<p>Sacha (<a href='http://twitter.com/sachagreif'>@SachaGreif</a>) is a french web and user experience designer. By the way, the fireman is in charge of shovelling coal into the engine.</p>"
            plate: "/samples/contents/sacha_plate.png"
            picture: "/samples/contents/conan.png"

    "Companies":
      description: Companies using Locomotive on a daily basis
      slug: companies
      order_by: manually
      highlighted_field_name: name
      fields:
        - name:
            hint: Company name
        - url:
            hint: "Website url (without the http://)"
        - logo:
            kind: file
            hint: "Image max width: 240px"
      contents:
        - "The Frontier Group":
            url: "www.thefrontiergroup.com.au"
            logo: "/samples/contents/companies/tfg.png"
        - "DesignHunger":
            url: "www.designhunger.de"
            logo: "/samples/contents/companies/designhunger.png"
        - "Experia":
            url: "www.experia.com.br"
            logo: "/samples/contents/companies/experia.png"

    "Modules":
      description: List all the modules sold in the locomotive website
      slug: modules
      order_by: manually
      highlighted_field_name: name
      fields:
        - name:
            hint: Module name
        - editor:
            hint: Person or company selling the module
        - price:
            hint: Integer without the euro symbol
        - short_description:
            hint: Short text displayed in the modules list page
        - description:
            hint: Long text displayed in the module page
            kind: text
        - license:
            hint: License options for the module
        - url:
            hint: "Link to the payment page without http://"
        - logo:
            kind: file
            hint: "Image size: 90px by 90px"
      contents:
        - "Locomotive Editor":
            editor: "Locomotive team"
            price: 30
            short_description: "Build your whole locomotive sites with your prefered IDE and import them once you are done."
            description: >
              The Locomotive editor is the perfect tool for your Locomotive websites. It lets you build fully Locomotive compliant websites with
              your prefered IDE without installing the whole Locomotive CMS stack. Your efficiency will be increased by a lot, we garantee you !
              <br/>
              <br/>
              We listed for you all the benefits of using our editor:
              <ul>
                <li><strong>Simple installation</strong>. MongoDB, RMagick, Rails, ...etc are not required. You only need Ruby.</li>
                <li><strong>Work with any IDE</strong>. We are sure you will agree with us, editing templates in a web browser is a real pain.</li>
                <li><strong>Define the custom content types</strong>. You create your content types in a YAML format.</li>
                <li><strong>Write your CSS with SASS</strong>. You are looking for more efficiency ? We integrated <a href="http://sass-lang.com/">SASS</a> for you.</li>
                <li><strong>Test your sites instantly</strong>. Just fire up your browser and you will see your changes.</li>
                <li><strong>Export your sites easily</strong>. Once you are done with a site, simply zip the folder and import it to your Locomotive instance</li>
                <li><strong>Version your work</strong>. Your templates and assets live now on your desktop so you can use GIT, SVN or any versionning tool.</li>
                <li><strong>Get frequently updates</strong>. Since we also develop sites like you do, we are always looking for higher efficiency and we have got plenty of ideas to make this product much better than it is right now.</li>
              </ul>
              <br/>
              <p>What does that include when you purchase our editor ?</p>
              <ul>
                <li>The editor itself packaged as a ruby gem</li>
                <li>Free upgrades for 1 year</li>
                <li>Free support for 1 year</li>
              </ul>

            license: "Licence valid for one user only.\n<a href='mailto:support@locomotivecms.com'>Contact us</a> for bulk orders."
            url: "www.yahoo.fr"
            logo: "/samples/contents/modules/editor.png"
        - "Statistics":
            editor: "Locomotive team"
            short_description: "coming soon"
            logo: "/samples/contents/modules/stats.png"
        - "Recurring Billing":
            editor: "Locomotive team"
            short_description: "coming soon"
            description: "Lorem ipsum"
            logo: "/samples/contents/modules/recurly.png"

    "Themes":
      description: List of built-in themes
      slug: themes
      order_by: manually
      highlighted_field_name: name
      fields:
        - name:
            hint: Name of the theme
        - author:
            hint: Company or person who built this theme
        - description:
            kind: text
            hint: Short description
        - license:
            hint: "Creative Commons Attribution 2.5 License, Commercial, ...etc"
        - url:
            hint: Original template url
        - screenshot:
            kind: file
            hint: Image (320px width)
        - zipfile:
            kind: file
            hint: Zip file people will use for the import
      contents:
        - "Html5/Css3 Portfolio":
            author: Tom Kenny
            description: "This is a simple portfolio website built with some HTML5 / CSS3 goodness. It comes from an excellent tutorial written by Tom Kenny."
            license: "-"
            url: http://inspectelement.com/tutorials/code-a-backwards-compatible-one-page-portfolio-with-html5-and-css3/
            screenshot: "/samples/contents/themes/html5_portfolio.png"
            zipfile: "/samples/contents/themes/html5_portfolio.zip"
        - "Lawyer&Attorney":
            author: Solucija
            description: "A sample website for a lawyer & attorney office."
            license: Creative Commons Attribution 2.5 License
            url: http://www.solucija.com/template/lawyerattorney
            screenshot: "/samples/contents/themes/lawyer.png"
            zipfile: "/samples/contents/themes/lawyer.zip"

  asset_collections:
    "Features screenshots":
      slug: features
      fields:
        - long_name:
            lable: "Title displayed in the features page"
        - short_description:
            kind: text
        - long_description:
            kind: text
        - thumb:
            label: "Thumb screenshot"
            kind: file
        - popup:
            label: "Popup"
            kind: boolean
            hint: "Enable the popup used to display the large screenshot"
        -  home:
            label: "Home page"
            kind: boolean
            hint: "Is this feature displayed in the home page ?"
        -  no_screenshot:
            label: "No screenshot"
            kind: boolean
            hint: "In case we do not have a vignette for this feature"
      assets:
        - "Custom content":
            url: "/samples/asset_collections/cc_large.jpg"
            thumb: "/samples/asset_collections/cc_thumb.png"
            long_name: Custom content types
            short_description: "Define your own content types: posts, events, videos..."
            long_description: |
              With most CMS, everything has to be blog posts (or pages, or articles) and building anything else requires hacks and plug-ins.
              <br/>Locomotive is different: it doesn't impose any specific data structure. Need a page for your band's discography?
              <br/>Create a new "recording" content type with a title, year, album cover, and track listing.
              <br/>Our custom content types are even enough flexible to build a contact form.
            popup: true
            home: true

        - "Multiple Sites":
            url: "/samples/asset_collections/ms_large.jpg"
            thumb: "/samples/asset_collections/ms_thumb.png"
            long_name: Multi sites support
            short_description: "Manage multiple sites with only one Locomotive install."
            long_description: |
              With a single instance of Locomotive, you can manage as many websites as your server can physically handle.
              <br/>Deploying a website becomes just a matter of pointing your website domain to your Locomotive server. No webserver tweaking, no application rebooting at all.
            popup: true
            home: true

        - "Templates":
            url: "/samples/asset_collections/coming_soon.png"
            long_name: Template inheritance with Liquid
            short_description: "Liquid templating language"
            long_description: |
              No need to learn one more weird syntax. We use Liquid, the most common templating language in Ruby. With <a href="http://www.liquidmarkup.org/">Liquid</a>, templates won't affect the security of your platform, and its syntax is simple to learn.
              <br/>Of course, since we are always looking for ways to improve things, we also tweaked it a lot.
              For instance, we added the notion of template inheritance that we took from <a href="http://docs.djangoproject.com/en/dev/topics/templates/">Python</a>.
              And we wrote a large collection of useful helper tags covering a large number of needs: google analytics snippet, pagination snippet for collections, helper to reach an
              external webservice and display contents from it, etc.
            no_screenshot: true
            popup: false
            home: false

        - "Sexy UI":
            url: "/samples/asset_collections/ui_large.jpg"
            thumb: "/samples/asset_collections/ui_thumb.png"
            long_name: Great user experience
            short_description: "Enjoy using a simple, clear and beautiful user interface."
            long_description: |
              We believe that user experience should not be get the short end of the stick in an open source application. So we put a lot of time into the user interface and global experience,
              and we often tweak things until they're just right.
              <br/>For instance, we recently added the CTRL+S shortcut to save a page in AJAX without refreshing.
            popup: true
            home: true

        - "Inline Editing":
            url: "/samples/asset_collections/coming_soon.png"
            thumb: "/samples/asset_collections/coming_soon.png"
            long_name: Inline front-end editing
            short_description: "Browse your site and edit a page at the same time."
            long_description: |
              When we discovered <a href="http://www.aloha-editor.org/">Aloha-Editor</a>, a very powerful and promising browser editor named, it was instantly clear for us that we had to integrate it into Locomotive !
              <br/>So Locomotive users can now define editable regions in their templates, and those regions can be edited by the end user directly from the page he's viewing.
            popup: false
            home: true

        - "Ruby On Rails":
            url: "/samples/asset_collections/rails.png"
            thumb: "/samples/asset_collections/rails.png"
            short_description: "Locomotive runs on the most powerful web framework."
            long_description: |
              We know that most people just want something that works, and don't care if it's written in Python, PHP, or Cobol.
              But in the case of Locomotive, we think its language is a huge asset.
              <br/>We built Locomotive with <a href="http://www.rubyonrails.org">Ruby on Rails 3</a>, which gives developers the ability to build their own application on top of the Locomotive engine.
              <br/>This means that Locomotive can be integrated in a wide range of applications Want to develop your own hosting websites platform? No problem!
            popup: false
            home: true

        - "In The Cloud":
            url: "/samples/asset_collections/heroku.png"
            thumb: "/samples/asset_collections/heroku.png"
            short_description: "Host Locomotive with Heroku, S3 and MongoHQ!"
            long_description: |
              Since we wanted people to be able to install Locomotive without setting up a server, we decided that Locomotive would run on <a href="http://www.heroku.com/">Heroku</a>, the famous ruby cloud platform.
              What's more, the database can also be hosted in the cloud (thanks to <a href="https://mongohq.com/">MongoHQ</a>),
              and all the files uploaded from Locomotive are stored on <a href="http://aws.amazon.com/s3/">Amazon S3</a>.
              <br/>With a such combination of powerful cloud services, we are able to host several websites for a couple of cents per month! But, of course, you are free to install on your server too !
            popup: false
            home: true
