site:
  locales: [en]

  meta_description: LOCOMOTIVE is an open source CMS for Rails. It's super flexible and integrates with Heroku and Amazon S3.
  meta_keywords: cms open source ruby on rails heroku liquid rails3 cloud amazon S3 inline editing
  name: Locomotive

  pages:
  - index:
      published: true
      title: Home
      listed: false
  - blog:
      published: true
      title: Blog
      listed: true
  - blog/content_type_template:
      templatized: true
      published: true
      title: Template of a blog post
      listed: true
      model: articles
  - company:
      published: true
      title: Company
      listed: true
  - features:
      published: true
      title: Features
      listed: true
  - gallery:
      published: true
      title: Gallery of Locomotive sites
      listed: true
  - license:
      published: true
      title: License
      listed: true
  - pricing:
      published: true
      title: Pricing
      listed: true
  - privacy-policy:
      published: true
      title: Privacy Policy
      listed: true
  - resources:
      published: true
      title: Resources
      listed: true
  - terms-of-use:
      published: true
      title: Terms Of Use
      listed: true
  - tour:
      published: true
      title: Tour
      listed: true
  - 404:
      published: true
      title: Page not found
      listed: true