site:
  locales: [en]

  meta_description: LOCOMOTIVE is an open source CMS for Rails. It's super flexible and integrates with Heroku and Amazon S3.
  meta_keywords: cms open source ruby on rails heroku liquid rails3 cloud amazon S3 inline editing
  name: Locomotive

  pages:
  - index:
      published: true
      title: Index
      listed: false
  - about_us:
      published: true
      title: About us
      listed: true
  - features:
      published: true
      title: Features
      listed: true
  - hosting:
      published: true
      title: Hosting
      listed: false
  - modules:
      published: true
      title: Modules
      listed: false
  - modules/content_type_template:
      templatized: true
      published: true
      title: Template of a module
      listed: true
      model: modules
  - documentation:
      published: true
      title: Documentation
      listed: true
      redirect_url: http://doc.locomotivecms.com
  - editor:
      published: true
      title: Editor
      listed: true
      redirect_url: /modules/locomotive-editor
  - articles:
      title: Blog
      published: true
      listed: true
  - articles/content_type_template:
      templatized: true
      published: true
      title: Template of an article
      model: articles
  - "404":
      published: true
      title: Page not found
      listed: true